require:
  - rubocop
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisabledByDefault: false
  NewCops: enable
  TargetRubyVersion: 2.6.3
  Exclude:
    - db/**/*
    - bin/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'db/migrate/*'
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Spec/InstanceVariable:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Max: 20
